"""
Markdown export utility for research reports.

Converts the structured report dict produced by report_node into a
well-formatted Markdown document suitable for download.
"""

from __future__ import annotations

from datetime import datetime


def to_markdown(
    report: dict,
    query: str,
    follow_up_questions: list[str] | None = None,
    contradictions: list[str] | None = None,
) -> str:
    """
    Convert a structured research report to a Markdown string.

    Parameters
    ----------
    report              : dict with keys title, abstract, findings,
                          sources, conclusion
    query               : original user research query
    follow_up_questions : optional list of follow-up question strings
    contradictions      : optional list of contradicting claims found

    Returns
    -------
    str — A formatted Markdown document ready for download.
    """
    now = datetime.now().strftime("%B %d, %Y at %H:%M")
    title = report.get("title", f"Research Report: {query}")
    abstract = report.get("abstract", "")
    findings = report.get("findings", [])
    sources = report.get("sources", [])
    conclusion = report.get("conclusion", "")

    lines: list[str] = []

    # Header
    lines += [
        f"# {title}",
        "",
        f"> **Query:** {query}  ",
        f"> **Generated:** {now}  ",
        f"> **Tool:** ScholarLens — Agentic AI Research Assistant",
        "",
        "---",
        "",
    ]

    # Abstract
    if abstract:
        lines += ["## Abstract", "", abstract, "", "---", ""]

    # Key Findings
    if findings:
        lines += ["## Key Findings", ""]
        for i, finding in enumerate(findings, 1):
            lines.append(f"{i}. {finding}")
        lines += ["", "---", ""]

    # Contradictions / Caveats
    if contradictions:
        lines += ["## ⚠️ Contradictions & Caveats", ""]
        for c in contradictions:
            lines.append(f"- {c}")
        lines += ["", "---", ""]

    # Conclusion
    if conclusion:
        lines += ["## Conclusion", "", conclusion, "", "---", ""]

    # Sources
    if sources:
        lines += ["## Sources", ""]
        for i, url in enumerate(sources, 1):
            lines.append(f"{i}. <{url}>")
        lines += ["", "---", ""]

    # Follow-up Questions
    if follow_up_questions:
        lines += ["## Follow-up Research Questions", ""]
        for q in follow_up_questions:
            lines.append(f"- {q}")
        lines += [""]

    # Footer
    lines += [
        "---",
        "",
        "*This report was automatically generated by ScholarLens using "
        "LangGraph, Groq (LLaMA 3.1), and DuckDuckGo search.*",
    ]

    return "\n".join(lines)
