"""
LangGraph state schema for the Agentic AI Research Assistant.

The ResearchState TypedDict is the single shared data structure that all
nodes read from and write to. LangGraph merges node outputs back into
this state automatically.
"""

from __future__ import annotations
from typing import TypedDict


class ResearchState(TypedDict):
    """
    Full state passed between every node in the research agent graph.

    Fields
    ------
    query               : The original user research question.
    search_results      : Raw results from DuckDuckGo [{title, url, snippet}].
    fetched_content     : Full page text fetched per URL [{url, content}].
    source_summaries    : Per-source LLM summaries [{url, summary}].
    validated_facts     : Cross-checked, consistent facts across sources.
    contradictions      : Statements that conflict between sources.
    report              : Final structured report dict.
    follow_up_questions : Suggested follow-up questions generated by the LLM.
    error               : Non-None when a fatal error occurred (e.g. no results).
    step_logs           : Human-readable progress messages shown in the UI.
    """
    query: str
    search_results: list[dict]       # [{title, url, snippet}]
    fetched_content: list[dict]      # [{url, content}]
    source_summaries: list[dict]     # [{url, summary}]
    validated_facts: list[str]
    contradictions: list[str]
    report: dict                     # {title, abstract, findings, sources, conclusion}
    follow_up_questions: list[str]
    error: str | None
    step_logs: list[str]
